CREATE TABLE user(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(50),
	pass VARCHAR(50),
	avatar BLOB,
	regDate date
);

CREATE TABLE comment(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	content VARCHAR(4000),
	comTime DATETIME,
	userId BIGINT NOT NULL,
	followId BIGINT,
	FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
);
