CREATE TABLE user(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(50),
	password VARCHAR(50),
	avata BLOB,
	regDate date
);

CREATE TABLE comment(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	content VARCHAR(4000),
	postTime DATETIME,
	userId BIGINT NOT NULL,
	followId BIGINT,
	FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
);
